app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError, Email, EqualTo
from ..models import User


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember_me = BooleanField("Remember Me")
    submit = SubmitField("Sign In")


class RegistrationForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    password2 = PasswordField(
        "Repeat Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Register")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError(
                f"Username {username.data} already registered. Please choose a different username"
            )

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError(
                f"An account already exists for {email.data}. Please use a different email address"
            )


class EditProfileForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    bio = TextAreaField("Biography", validators=[Length(min=0, max=256)])
    submit = SubmitField("Submit")

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if self.original_username == username.data:
            return
        user_count = User.query.filter_by(username=username.data).count()
        if user_count > 0:
            raise ValidationError(
                f"Username {username.data} is already registered. Please choose a different username"
            )

app/user/__init__.py
from flask import Blueprint

bp = Blueprint("user", __name__)

from . import routes

app/user/routes.py
from datetime import datetime, date
from flask import render_template, url_for, flash, redirect, request, abort, current_app
from flask_login import current_user, login_user, logout_user, login_required
from sqlalchemy.exc import MultipleResultsFound
from .. import db
from ..models import User
from . import bp
from .forms import LoginForm, RegistrationForm, EditProfileForm


@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_active = datetime.utcnow()
        db.session.commit()


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            current_app.logger.debug("/login - Unsuccessful login for {form.username}")
            flash("Invalid username or password")
            return redirect(url_for("user.login"))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            return redirect(url_for("main.index"))
        return redirect(url_for(next_page))
    return render_template("user/login.html", title="Sign In", form=form)


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Congratulations, you're now registered!")
        current_app.logger.info(f"/register - {form.username.data}")
        return redirect(url_for("main.index"))
    return render_template("user/register.html", title="Register", form=form)


@bp.route("/user/<username>")
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template("user/user.html", user=user, css="person.css")


@bp.route("/edit_profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash("Your changes have been saved")
        return redirect(url_for("user.user", username=current_user.username))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.bio.data = current_user.bio
    return render_template("user/edit_profile.html", title="Edit Profile", form=form)

app/templates/user/edit_profile.html
{% extends "base.html" %}
{% block content %}
<h1>Edit Profile</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div>
            {{ form.username.label }} <br/>
            {{ form.username(size=32) }} 
            {% for error in form.username.errors %}
            <br/><span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.bio.label }} <br/>
            {{ form.bio(size=64) }}
            {% for error in form.bio.errors %}
            <br/><span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.submit() }}
        </div>
    </form>
{% endblock %}

app/templates/user/login.html
{% extends "base.html" %}

{% block content %}
<h1> Sign In </h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div>
            {{ form.username.label }} <br/>
            {{ form.username(size=32) }} 
            {% for error in form.username.errors %}
            <br/><span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }} <br/>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <br/><span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.remember_me() }} {{ form.remember_me.label }} 
        </div>
        <div>
            {{ form.submit() }}
        </div>
    </form>
    <p>New User?
        <a href="{{ url_for('user.register') }}">Click here to register</a>
    </p>
{% endblock %}

app/templates/user/register.html
{% extends "base.html" %}

{% block content %}
<h1>Register</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div>
            {{ form.username.label }} <br/>
            {{ form.username(size=32) }} 
            {% for error in form.username.errors %}
            <br/><span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.email.label }} <br/>
            {{ form.email(size=64) }}
            {% for error in form.email.errors %}
            <br/><span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }} <br/>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <br/><span class="error">[{{ error }}]</span>
            {% endfor %}
        <div>
            {{ form.password2.label }} <br/>
            {{ form.password2(size=32) }}
            {% for error in form.password2.errors %}
            <br/><span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.submit() }}
        </div>
    </form>
{% endblock %}

app/templates/user/user.html
{% extends "base.html" %}

{% block content %}
<div class="user">
    {{ user.username }}
</div>
<div>
    {% if user.bio %}
    <div><strong>About Me:</strong> {{ user.bio }}</div>
    {% endif %}
    {% if user.last_active %}
    <div><strong>Last Logon:</strong> {{ user.last_active }}</div>
    {% endif %}
</div>
{% if user == current_user %}
<p><a href="{{ url_for('user.edit_profile') }}">Edit profile</a></p>
{% endif %}
{% endblock %}